"""geblesseerd_tot toevoegen aan huisdieren

Revision ID: 3da247af4108
Revises: 7ad38eeae8ff
Create Date: 2026-07-22 20:27:33.872718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da247af4108'
down_revision: Union[str, Sequence[str], None] = '7ad38eeae8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huisdieren', sa.Column('geblesseerd_tot', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huisdieren', 'geblesseerd_tot')
    # ### end Alembic commands ###
