"""pet volgnummer per speler toevoegen

Revision ID: 4a81b4aab69b
Revises: 3da247af4108
Create Date: 2026-07-22 21:13:44.598886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a81b4aab69b'
down_revision: Union[str, Sequence[str], None] = '3da247af4108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huisdieren', sa.Column('volgnummer', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_huisdieren_eigenaar_volgnummer', 'huisdieren', ['eigenaar_id', 'volgnummer'])
    op.add_column('spelers', sa.Column('volgend_pet_nummer', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spelers', 'volgend_pet_nummer')
    op.drop_constraint('uq_huisdieren_eigenaar_volgnummer', 'huisdieren', type_='unique')
    op.drop_column('huisdieren', 'volgnummer')
    # ### end Alembic commands ###
