"""werk kanaal id toevoegen voor tag-notificatie

Revision ID: 4faaffe78404
Revises: 82e96ebcfcf8
Create Date: 2026-07-20 16:26:29.703369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4faaffe78404'
down_revision: Union[str, Sequence[str], None] = '82e96ebcfcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huisdieren', sa.Column('werk_kanaal_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huisdieren', 'werk_kanaal_id')
    # ### end Alembic commands ###
