"""afbeelding_url toevoegen aan pet_soorten

Revision ID: 5acfb2f199ac
Revises: f8a0644dff33
Create Date: 2026-07-20 13:57:32.080332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acfb2f199ac'
down_revision: Union[str, Sequence[str], None] = 'f8a0644dff33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_soorten', sa.Column('afbeelding_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_soorten', 'afbeelding_url')
    # ### end Alembic commands ###
