"""ranked daglimiet velden toevoegen aan spelers

Revision ID: 7ad38eeae8ff
Revises: 80b9e9f28e82
Create Date: 2026-07-22 20:19:56.567020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad38eeae8ff'
down_revision: Union[str, Sequence[str], None] = '80b9e9f28e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'spelers', sa.Column('ranked_pogingen_vandaag', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column('spelers', sa.Column('ranked_reset_op', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spelers', 'ranked_reset_op')
    op.drop_column('spelers', 'ranked_pogingen_vandaag')
    # ### end Alembic commands ###
