"""laatste_slaap_op toevoegen voor slaap-cooldown

Revision ID: 80b9e9f28e82
Revises: 815bfed28306
Create Date: 2026-07-22 14:54:10.564769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b9e9f28e82'
down_revision: Union[str, Sequence[str], None] = '815bfed28306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huisdieren', sa.Column('laatste_slaap_op', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huisdieren', 'laatste_slaap_op')
    # ### end Alembic commands ###
