"""xp veld toevoegen aan huisdieren

Revision ID: 815bfed28306
Revises: 9d3f2b6a7c41
Create Date: 2026-07-22 14:25:11.678909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815bfed28306'
down_revision: Union[str, Sequence[str], None] = '9d3f2b6a7c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huisdieren', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huisdieren', 'xp')
    # ### end Alembic commands ###
