"""werk notificatie vlag toevoegen

Revision ID: 82e96ebcfcf8
Revises: 9412675b2bd0
Create Date: 2026-07-20 16:21:25.792093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e96ebcfcf8'
down_revision: Union[str, Sequence[str], None] = '9412675b2bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'huisdieren',
        sa.Column('werk_notificatie_verstuurd', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huisdieren', 'werk_notificatie_verstuurd')
    # ### end Alembic commands ###
