"""werk-laag velden toevoegen

Revision ID: 9412675b2bd0
Revises: 5acfb2f199ac
Create Date: 2026-07-20 16:09:29.004141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9412675b2bd0'
down_revision: Union[str, Sequence[str], None] = '5acfb2f199ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huisdieren', sa.Column('werk_cyclus', sa.String(length=16), nullable=True))
    op.add_column('huisdieren', sa.Column('werk_gestart_op', sa.DateTime(), nullable=True))
    op.add_column('werkplekken', sa.Column('opbrengst_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'werkplekken', 'items', ['opbrengst_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'werkplekken', type_='foreignkey')
    op.drop_column('werkplekken', 'opbrengst_item_id')
    op.drop_column('huisdieren', 'werk_gestart_op')
    op.drop_column('huisdieren', 'werk_cyclus')
    # ### end Alembic commands ###
