"""initial schema

Revision ID: dc11fdd51496
Revises: 
Create Date: 2026-07-20 12:21:49.764010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc11fdd51496'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instellingen',
    sa.Column('sleutel', sa.String(length=64), nullable=False),
    sa.Column('waarde', sa.String(length=256), nullable=False),
    sa.Column('beschrijving', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('sleutel')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('voeding', 'materiaal', 'grondstof', 'boost', 'overig', name='item_type'), nullable=False),
    sa.Column('beschrijving', sa.String(length=256), nullable=True),
    sa.Column('prijs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('spelers',
    sa.Column('discord_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('mmr', sa.Integer(), nullable=False),
    sa.Column('gilde_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('naam', sa.String(length=32), nullable=False),
    sa.Column('spawnkans', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stat_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('werkplekken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('vereiste_werk_genen', sa.String(length=32), nullable=False),
    sa.Column('output_per_uur', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('capaciteit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('inventaris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speler_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('aantal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['speler_id'], ['spelers.discord_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speler_id', 'item_id', name='uq_inventaris_speler_item')
    )
    op.create_table('pet_soorten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=64), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('gevecht_basis', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('werk_basis', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('werkplek_voorkeur_id', sa.Integer(), nullable=True),
    sa.Column('beschrijving', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['werkplek_voorkeur_id'], ['werkplekken.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('huisdieren',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eigenaar_id', sa.BigInteger(), nullable=False),
    sa.Column('soort_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=32), nullable=False),
    sa.Column('honger', sa.Integer(), nullable=False),
    sa.Column('energie', sa.Integer(), nullable=False),
    sa.Column('blijdschap', sa.Integer(), nullable=False),
    sa.Column('gevecht_genen', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('werk_genen', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('team', 'werkplek', 'rust', name='pet_status'), nullable=False),
    sa.Column('werkplek_type_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eigenaar_id'], ['spelers.discord_id'], ),
    sa.ForeignKeyConstraint(['soort_id'], ['pet_soorten.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['werkplek_type_id'], ['werkplekken.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('huisdieren')
    op.drop_table('pet_soorten')
    op.drop_table('inventaris')
    op.drop_table('werkplekken')
    op.drop_table('tiers')
    op.drop_table('spelers')
    op.drop_table('items')
    op.drop_table('instellingen')
    # ### end Alembic commands ###
